name: Docker

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main

jobs:
  # Push image to Docker Hub.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    name: "Push to docker"
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: dheerajkhardwal/maven-aws
          tag_with_ref: true
          file: openjdk-8-slim/Dockerfile
          push: true
