name: openjdk-11-slim

on:
  push:
    # Publish `main` as Docker `latest` image.
    branches:
      - main
    paths:
      - 'openjdk-11-slim/**'

jobs:
  # Push image to Docker Hub.
  # See also https://docs.docker.com/docker-hub/builds/
  push:
    name: "Push to docker"
    runs-on: ubuntu-latest

    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: ./openjdk-11-slim/Dockerfile
          push: true
          tags: dheerajkhardwal/maven-aws:openjdk-11-slim